//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleRental.Data.Model.Entities.Repositories
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IVehicleImageRepository : SkyWeb.DatVM.Data.IBaseRepository<VehicleImage>
    {
    }
    
    public partial class VehicleImageRepository : SkyWeb.DatVM.Data.BaseRepository<VehicleImage>, IVehicleImageRepository
    {
    	public VehicleImageRepository(System.Data.Entity.DbContext dbContext) : base(dbContext)
        {
        }
    }
}
