//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleRental.Data.Model.Entities.Repositories
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IVehicleTypeRepository : SkyWeb.DatVM.Data.IBaseRepository<VehicleType>
    {
    }
    
    public partial class VehicleTypeRepository : SkyWeb.DatVM.Data.BaseRepository<VehicleType>, IVehicleTypeRepository
    {
    	public VehicleTypeRepository(System.Data.Entity.DbContext dbContext) : base(dbContext)
        {
        }
    }
}
