//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleRental.Data.Model.Entities.Service
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IVehicleTypeService : SkyWeb.DatVM.Data.IBaseService<VehicleType>
    {
    }
    
    public partial class VehicleTypeService : SkyWeb.DatVM.Data.BaseService<VehicleType>, IVehicleTypeService
    {
        public VehicleTypeService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IVehicleTypeRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
