//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleRental.Data.Model.Entities.Service
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IVehicleImageService : SkyWeb.DatVM.Data.IBaseService<VehicleImage>
    {
    }
    
    public partial class VehicleImageService : SkyWeb.DatVM.Data.BaseService<VehicleImage>, IVehicleImageService
    {
        public VehicleImageService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IVehicleImageRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
