//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleRental.Data.Model.Entities.Service
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IVehicleService : SkyWeb.DatVM.Data.IBaseService<Vehicle>
    {
    }
    
    public partial class VehicleService : SkyWeb.DatVM.Data.BaseService<Vehicle>, IVehicleService
    {
        public VehicleService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IVehicleRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
