//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleRental.Data.Model.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrandViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<VehicleRental.Data.Model.Entities.Brand>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual string BrandName { get; set; }
    	
    	public BrandViewModel() : base() { }
    	public BrandViewModel(VehicleRental.Data.Model.Entities.Brand entity) : base(entity) { }
    
    }
}
