//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleRental.Data.Model.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<VehicleRental.Data.Model.Entities.Order>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual int VehicleId { get; set; }
    			public virtual string Name { get; set; }
    			public virtual string IdentifyId { get; set; }
    			public virtual string Phone { get; set; }
    			public virtual string Address { get; set; }
    			public virtual string AddressDeliver { get; set; }
    			public virtual Nullable<System.DateTime> RentDate { get; set; }
    			public virtual Nullable<System.DateTime> ReturnDate { get; set; }
    			public virtual Nullable<bool> IsActive { get; set; }
    	
    	public OrderViewModel() : base() { }
    	public OrderViewModel(VehicleRental.Data.Model.Entities.Order entity) : base(entity) { }
    
    }
}
