//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleRental.Data.Model.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<VehicleRental.Data.Model.Entities.User>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual string Name { get; set; }
    			public virtual string IdentifyId { get; set; }
    			public virtual string Address { get; set; }
    			public virtual string Phone { get; set; }
    			public virtual Nullable<System.DateTime> Birthday { get; set; }
    			public virtual Nullable<bool> Sex { get; set; }
    			public virtual string Username { get; set; }
    			public virtual string Password { get; set; }
    			public virtual Nullable<bool> IsAdmin { get; set; }
    			public virtual Nullable<bool> IsActive { get; set; }
    	
    	public UserViewModel() : base() { }
    	public UserViewModel(VehicleRental.Data.Model.Entities.User entity) : base(entity) { }
    
    }
}
