//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleRental.Data.Model.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleImageViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<VehicleRental.Data.Model.Entities.VehicleImage>
    {
    	
    			public virtual Nullable<int> VehicleId { get; set; }
    			public virtual string ImageUrl { get; set; }
    			public virtual int id { get; set; }
    	
    	public VehicleImageViewModel() : base() { }
    	public VehicleImageViewModel(VehicleRental.Data.Model.Entities.VehicleImage entity) : base(entity) { }
    
    }
}
